### ISSUE TITLE
Set up event to share about PyMC v4.0 release

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/brand#12]
Not sure where the best place to open up the issue is.

(Tangential thought: wondering if we should rename this repo "community" or something).

Back to the topic:  
- Set a date and speaker to discuss in more details the v4.0 release
- Once a date is set, set up Meetup event
- Do social media card and promotion

cc:  @twiecki @cluhmann @OriolAbril

**Comment by cluhmann** [comment]
Is this completed with Ricardo's talk scheduled?  Or were you thinking about something different/more?

**Comment by reshamas** [comment]
Closing this issue, as it is now a bit outdated.
