### ISSUE TITLE
NumFOCUS donation link: update from "pymc3" to "pymc"?

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/brand#3]
Current URL is:  
https://numfocus.org/donate-to-pymc3

Should we ask them to update it to PyMC and make the change everywhere?

**Comment by twiecki** [comment]
Yes, definitely.

**Comment by reshamas** [comment]
@OriolAbril @twiecki 

Here is where the "pymc3" shows up in the URL.  I believe it can be changed at the "organization" level, rather than each "repo" level, but I am not really sure.

Ref:  https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-organization

---

<img width="1167" alt="Screen Shot 2022-07-21 at 11 57 52 AM" src="https://user-images.githubusercontent.com/2507232/180260736-73f09785-caf4-4f0c-8630-7dbe789b3615.png">

**Comment by OriolAbril** [comment]
This is already configured at the org level: https://github.com/pymc-devs/.github/blob/main/FUNDING.yml

**Comment by reshamas** [comment]
@twiecki @OriolAbril 
So, then we just need to update the URL here:
`pymc3` to `pymc`:  
```
github: numfocus
custom: ['https://numfocus.org/donate-to-pymc3'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
```

**Comment by reshamas** [comment]
@twiecki @OriolAbril 
DONE !!!!!!!
